# Пользователи
## Создание

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

###

## Авторизация

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

###

## Отправить изображение

POST http://localhost:5000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\Dmitriy\Desktop\screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###

## Токен
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczFAb3Zlcmxvb2submV0IiwibmFtZSI6IkphY2siLCJpZCI6IjY2NTMyZDgwYWVkYWE4YWM4NDkwODhlOCIsImlhdCI6MTcxNjcyNzE4NCwiZXhwIjoxNzE2ODk5OTg0fQ.QvoXNmtM_QE7TddcVTOwOiWKmf4qFAJ7DkU1w_H3aE8

###
